on: [push]
jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v4
    - name: Hello world action step
      id: caller
      uses: lipingtababa/actionsplayground@v1
      with:
        who-to-greet: 'Mona the Octocat'
    - name: Get the output 
      run: echo random-number is ${{ steps.caller.outputs.random-number }}